deployment:
  tasks:
    - export DEPLOYPATH=/home/u1762120/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R resume $DEPLOYPATH
